package spider.mglp.pojo;

import java.util.Date;

public class ProductSpu {

    private Integer id;

    private String spuCode;

    private String spuUid;

    private String brandStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.title
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.fabric_composition
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String fabricComposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.fabric_type
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Integer fabricType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.season
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String season;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.style_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String styleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.brand_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.vendor_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Integer vendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.max_class_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Integer maxClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.class_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.price
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.sales_price
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Integer salesPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.price_cat
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String priceCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.color
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.ppe_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String ppeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.image
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.taobao_link
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String taobaoLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.taobao_image
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String taobaoImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.store_spu_code
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String storeSpuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.brand_color
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private String brandColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.c_time
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.ts
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Date ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_spu.if_download
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    private Boolean ifDownload;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.id
     *
     * @return the value of product_spu.id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.id
     *
     * @param id the value for product_spu.id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.spu_code
     *
     * @return the value of product_spu.spu_code
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getSpuCode() {
        return spuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.spu_code
     *
     * @param spuCode the value for product_spu.spu_code
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setSpuCode(String spuCode) {
        this.spuCode = spuCode == null ? null : spuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.spu_uid
     *
     * @return the value of product_spu.spu_uid
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getSpuUid() {
        return spuUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.spu_uid
     *
     * @param spuUid the value for product_spu.spu_uid
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setSpuUid(String spuUid) {
        this.spuUid = spuUid == null ? null : spuUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.brand_style
     *
     * @return the value of product_spu.brand_style
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getBrandStyle() {
        return brandStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.brand_style
     *
     * @param brandStyle the value for product_spu.brand_style
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setBrandStyle(String brandStyle) {
        this.brandStyle = brandStyle == null ? null : brandStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.title
     *
     * @return the value of product_spu.title
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.title
     *
     * @param title the value for product_spu.title
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.fabric_composition
     *
     * @return the value of product_spu.fabric_composition
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getFabricComposition() {
        return fabricComposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.fabric_composition
     *
     * @param fabricComposition the value for product_spu.fabric_composition
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setFabricComposition(String fabricComposition) {
        this.fabricComposition = fabricComposition == null ? null : fabricComposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.fabric_type
     *
     * @return the value of product_spu.fabric_type
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getFabricType() {
        return fabricType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.fabric_type
     *
     * @param fabricType the value for product_spu.fabric_type
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setFabricType(Integer fabricType) {
        this.fabricType = fabricType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.season
     *
     * @return the value of product_spu.season
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.season
     *
     * @param season the value for product_spu.season
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setSeason(String season) {
        this.season = season == null ? null : season.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.style_id
     *
     * @return the value of product_spu.style_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.style_id
     *
     * @param styleId the value for product_spu.style_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setStyleId(String styleId) {
        this.styleId = styleId == null ? null : styleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.brand_id
     *
     * @return the value of product_spu.brand_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.brand_id
     *
     * @param brandId the value for product_spu.brand_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.vendor_id
     *
     * @return the value of product_spu.vendor_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.vendor_id
     *
     * @param vendorId the value for product_spu.vendor_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.max_class_id
     *
     * @return the value of product_spu.max_class_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getMaxClassId() {
        return maxClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.max_class_id
     *
     * @param maxClassId the value for product_spu.max_class_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setMaxClassId(Integer maxClassId) {
        this.maxClassId = maxClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.class_id
     *
     * @return the value of product_spu.class_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.class_id
     *
     * @param classId the value for product_spu.class_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.price
     *
     * @return the value of product_spu.price
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.price
     *
     * @param price the value for product_spu.price
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.sales_price
     *
     * @return the value of product_spu.sales_price
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public Integer getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.sales_price
     *
     * @param salesPrice the value for product_spu.sales_price
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setSalesPrice(Integer salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.price_cat
     *
     * @return the value of product_spu.price_cat
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getPriceCat() {
        return priceCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.price_cat
     *
     * @param priceCat the value for product_spu.price_cat
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setPriceCat(String priceCat) {
        this.priceCat = priceCat == null ? null : priceCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.color
     *
     * @return the value of product_spu.color
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.color
     *
     * @param color the value for product_spu.color
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.ppe_id
     *
     * @return the value of product_spu.ppe_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getPpeId() {
        return ppeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.ppe_id
     *
     * @param ppeId the value for product_spu.ppe_id
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setPpeId(String ppeId) {
        this.ppeId = ppeId == null ? null : ppeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.image
     *
     * @return the value of product_spu.image
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.image
     *
     * @param image the value for product_spu.image
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.taobao_link
     *
     * @return the value of product_spu.taobao_link
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getTaobaoLink() {
        return taobaoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.taobao_link
     *
     * @param taobaoLink the value for product_spu.taobao_link
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setTaobaoLink(String taobaoLink) {
        this.taobaoLink = taobaoLink == null ? null : taobaoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.taobao_image
     *
     * @return the value of product_spu.taobao_image
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getTaobaoImage() {
        return taobaoImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_spu.taobao_image
     *
     * @param taobaoImage the value for product_spu.taobao_image
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public void setTaobaoImage(String taobaoImage) {
        this.taobaoImage = taobaoImage == null ? null : taobaoImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_spu.store_spu_code
     *
     * @return the value of product_spu.store_spu_code
     *
     * @mbg.generated Wed Jul 11 11:43:57 CST 2018
     */
    public String getStoreSpuCode() {
        return storeSpuCode;
    }

    public void setStoreSpuCode(String storeSpuCode) {
        this.storeSpuCode = storeSpuCode == null ? null : storeSpuCode.trim();
    }

    public String getBrandColor() {
        return brandColor;
    }

    public void setBrandColor(String brandColor) {
        this.brandColor = brandColor == null ? null : brandColor.trim();
    }

    public Date getcTime() {
        return cTime;
    }

    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    public Date getTs() {
        return ts;
    }


    public void setTs(Date ts) {
        this.ts = ts;
    }


    public Boolean getIfDownload() {
        return ifDownload;
    }


    public void setIfDownload(Boolean ifDownload) {
        this.ifDownload = ifDownload;
    }
}